In [2]:
!pip install numpy

In [11]:
import numpy as np

In [4]:
arrl=np.array([1,2,3,4,5])

In [5]:
arrl

array([1, 2, 3, 4, 5])

In [7]:
type(arrl)

numpy.ndarray

In [8]:
print(arrl.ndim)

1


In [11]:
arr2=np.array(([1,2,3],[4,5,6]))

In [13]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
print(arr2.ndim)

2


In [16]:
arr3=np.zeros((2,3))

In [18]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
print(arr3.ndim)

2


In [7]:
arr4=np.ones((3,3))

In [8]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr1=np.array([1,2,3,4,5])
print(arr1[0])

1


In [11]:
arr1[3]

np.int64(4)

In [13]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

print(arr2[0,1])

In [14]:
arr7=np.array([1,2,3,4,5,6,7])
print(arr7[1:5:2])

[2 4]


In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [21]:
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [3]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr =np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [5]:
arr1=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [6]:
arr1=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [15]:
from numpy import random
x=random.randint(100)
print(x)

7


In [16]:
x=random.rand()
print(x)

0.6660663984626454


In [17]:
x=random.randint(100,size=(5))
print(x)

[62 44 60 36 99]


In [18]:
x=random.randint(100,size=(3,5))
print(x) 

[[64 84 42 45 60]
 [34 32  4 31 53]
 [40  6  6  6 24]]


In [19]:
x=random.rand(5)
print(x)

[0.32403803 0.49241471 0.91306398 0.49920908 0.7859457 ]
